services:
  - type: web
    name: truck-optimizer
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /_stcore/health
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHONUNBUFFERED
        value: "1" 